### ISSUE TITLE
Unable to check for plugin updates

### ISSUE THREAD

**Issue by jelovac** [flathub/org.apache.netbeans#3]
Hi,

I have noticed that updating available plugins list is currently not working, throws the following error:

> Unable to connect to the NetBeans Distribution because of Received fatal alert: handshake_failure

![screenshot at 2018-11-10 18-39-26](https://user-images.githubusercontent.com/3627139/48304312-10491180-e518-11e8-879f-d66ff3ecb357.png)

Best regards,
Vladimir

**Comment by jelovac** [comment]
Additional info from the cli:

> INFO [org.netbeans.modules.autoupdate.updateprovider.DownloadListener]: Reading URL https://netbeans.apache.org/nb/updates/9.0/updates.xml.gz?unique=0ee1b4d0d-e69e-49b0-9aae-3ed2eab8dc64_1d9e6a63-2d79-4aec-b3d6-d682b873c4fc failed (javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure)
INFO [org.netbeans.modules.autoupdate.ui.Utilities]: Received fatal alert: handshake_failure
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at java.base/sun.security.ssl.Alerts.getSSLException(Alerts.java:198)
	at java.base/sun.security.ssl.Alerts.getSSLException(Alerts.java:159)
	at java.base/sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2046)
	at java.base/sun.security.ssl.SSLSocketImpl.processInputRecord(SSLSocketImpl.java:1207)
	at java.base/sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1074)
	at java.base/sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
	at java.base/sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1402)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1429)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:163)
	at org.netbeans.modules.autoupdate.updateprovider.NetworkAccess.checkRedirect(NetworkAccess.java:240)
	at org.netbeans.modules.autoupdate.updateprovider.NetworkAccess.access$700(NetworkAccess.java:57)
	at org.netbeans.modules.autoupdate.updateprovider.NetworkAccess$Task$2.call(NetworkAccess.java:160)
	at org.netbeans.modules.autoupdate.updateprovider.NetworkAccess$Task$2.call(NetworkAccess.java:138)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused: java.io.IOException: Received fatal alert: handshake_failure
	at org.netbeans.modules.autoupdate.updateprovider.DownloadListener.notifyException(DownloadListener.java:78)
	at org.netbeans.modules.autoupdate.updateprovider.AutoupdateCatalogCache.copy(AutoupdateCatalogCache.java:221)
	at org.netbeans.modules.autoupdate.updateprovider.AutoupdateCatalogCache.writeCatalogToCache(AutoupdateCatalogCache.java:74)
	at org.netbeans.modules.autoupdate.updateprovider.AutoupdateCatalogProvider.refresh(AutoupdateCatalogProvider.java:129)
	at org.netbeans.modules.autoupdate.services.UpdateUnitProviderImpl.refresh(UpdateUnitProviderImpl.java:155)
	at org.netbeans.api.autoupdate.UpdateUnitProvider.refresh(UpdateUnitProvider.java:171)
[catch] at org.netbeans.modules.autoupdate.ui.Utilities.tryRefreshProviders(Utilities.java:408)
	at org.netbeans.modules.autoupdate.ui.Utilities.doRefreshProviders(Utilities.java:386)
	at org.netbeans.modules.autoupdate.ui.Utilities.presentRefreshProviders(Utilities.java:380)
	at org.netbeans.modules.autoupdate.ui.UnitTab$14.run(UnitTab.java:781)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)

**Comment by jelovac** [comment]
Update: Removed the flatpak version and tested with Apache NetBeans compiled binaries, the updater works without issues.

**Comment by patriziobruno** [comment]
Hi @jelovac, the root CA for netbeans.apache.org is not in the openjdk's trust list. You can workaround the problem by changing to http the Netbeans Distribution's URL in Tools->Plugins->Settings.

**Comment by patriziobruno** [comment]
Apparently openjdk11 has a more comprehensive certificate store, no more https exceptions when updating plugins
